name: Continuous Integration

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master
jobs:
  Test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        versions:
          - elixir: "1.16"
            otp: "26"
          - elixir: "1.17"
            otp: "27"
          - elixir: "1.18"
            otp: "27"
    env:
      MIX_ENV: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.versions.otp}}
          elixir-version: ${{matrix.versions.elixir}}

      - name: Install Dependencies
        run: |
          mix deps.get

      - name: Run Tests
        run: mix test

  Linting:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}} Linting
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.16"
          otp-version: "26"

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Run Formatter
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo
